Algoritmo "Aula_07_Condicional_Composta_Exercicio 2"

Var
     N1,N2,Media:Real
Inicio
      Escreva ("Informe a primeira nota do Aluno: ")
      Leia(N1)
      Escreva ("Informe a segunda nota do Aluno: ")
      Leia (N2)
      Media<-(N1+N2)/2
      Escreval ("A média do aluno é :", Media:8:1)
       Se (Media>=7) Entao
        Escreva("O Aluno está Aprovado")
       Senao
        Escreva("O Aluno está Resprovado")
       FimSe
Fimalgoritmo