Algoritmo "Exercicio_26"

Var
   N1,N2:Inteiro
Inicio
  Escreva("Informe um numero inteiro: ")
  Leia(N1)
  Escreva("Informe outro numero inteiro: ")
  Leia (N2)
       Se(N1=N2) Entao
        Escreva(N1," e",N2," São IGUAIS")
       Senao
            Se(N1<N2)Entao
             Escreva(N1," é MENOR que ",N2)
            Senao
             Escreva(N1," é MAIOR que ",N2)
            FImse
       Fimse
Fimalgoritmo